name: arenda

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: pip install requests markdownify beautifulsoup4
      - run: python arenda.py
        env:
          JINA_KEY: ${{ secrets.JINA_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID_ARENDA: ${{ secrets.TELEGRAM_CHAT_ID_ARENDA }}
